apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Oracle JDK 8
    openshift.io/image.dockerRepositoryCheck: 2017-08-14T08:27:08Z
  creationTimestamp: null
  generation: 2
  name: oracle-jdk18-openshift
spec:
  dockerImageRepository: registry.access.redhat.com/oracle-jdk-18/jdk18-openshift
  tags:
  - annotations:
      description: Build and run Java applications using Maven and Oracle JDK 8.
      iconClass: icon-jboss
      openshift.io/display-name: Oracle JDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,xpaas:1.0
      tags: builder,java,xpaas,oraclejdk
      version: "latest"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/oracle-jdk-18/jdk18-openshift:latest
    generation: 2
    importPolicy:
      insecure: true
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
